export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const USER_LOADED = 'USER_LOADED';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const GET_PET_PROFILE = 'GET_PET_PROFILE';
export const UPDATE_PET_PROFILE = 'UPDATE_PET_PROFILE';
export const DELETE_PET_PROFILE = 'DELETE_PET_PROFILE';
export const CLEAR_PET_PROFILE = 'CLEAR_PET_PROFILE';

export const GET_ALL_PET_PROFILES = 'GET_ALL_PET_PROFILES';
export const CLEAR_ALL_PET_PROFILES = 'CLEAR_ALL_PET_PROFILES';

export const GET_ADMINS_PET_PROFILES = 'GET_ADMINS_PET_PROFILES';
export const CLEAR_ADMINS_PET_PROFILES = 'CLEAR_ADMINS_PET_PROFILES';

export const GET_LATEST_PET_UPDATE_PROFILES = 'GET_LATEST_PET_UPDATE_PROFILES';